# Generated by Django 4.0.6 on 2022-10-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Erno', models.IntegerField()),
                ('Dept', models.CharField(choices=[('CE', 'CE'), ('IT', 'IT')], max_length=10)),
                ('College', models.CharField(max_length=50)),
            ],
        ),
    ]
