# Generated by Django 4.0.6 on 2022-10-21 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='crud',
            new_name='sinfo',
        ),
    ]
